name: GPT Workflow

on: workflow_dispatch

permissions:
  pull-requests: write
  contents: write

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run GPT Prompt
        uses: DukeLuo/gpt-runner@main
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          cmd: promptr -m gpt-3.5-turbo -p "You are a super developer who is fluent in both Chinese and English. Please create a new file called README_zh.md with the Chinese translation of README.md"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: add-readme-zh
          title: "docs: Add README_zh.md"
          commit-message: "docs: Add README_zh.md"
